version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html/storage
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  app_data: