global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'php'
    static_configs:
      - targets: ['php:80']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

